# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chicago-etl}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Roland Swingler}]
  s.date = %q{2012-09-26}
  s.description = %q{ETL tools for Chicago}
  s.email = %q{roland.swingler@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "chicago-etl.gemspec",
    "lib/chicago-etl.rb",
    "lib/chicago/etl.rb",
    "lib/chicago/etl/batch.rb",
    "lib/chicago/etl/batched_dataset_filter.rb",
    "lib/chicago/etl/key_builder.rb",
    "lib/chicago/etl/mysql_dumpfile_writer.rb",
    "lib/chicago/etl/table_builder.rb",
    "lib/chicago/etl/task_invocation.rb",
    "lib/chicago/etl/tasks.rb",
    "spec/db_connections.yml.dist",
    "spec/etl/batch_spec.rb",
    "spec/etl/batched_dataset_filter_spec.rb",
    "spec/etl/key_builder_spec.rb",
    "spec/etl/mysql_dumpfile_writer_spec.rb",
    "spec/etl/table_builder_spec.rb",
    "spec/etl/task_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/notonthehighstreet/chicago-etl}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Chicago ETL}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chicagowarehouse>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<flog>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<chicagowarehouse>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2"])
      s.add_dependency(%q<timecop>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<flog>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<chicagowarehouse>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2"])
    s.add_dependency(%q<timecop>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<flog>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

