# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chicago-flow"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roland Swingler"]
  s.date = "2013-06-05"
  s.description = "Dataflow-style processing for hash-like rows"
  s.email = "roland.swingler@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/chicago/flow.rb",
    "lib/chicago/flow/array_sink.rb",
    "lib/chicago/flow/array_source.rb",
    "lib/chicago/flow/dataset_source.rb",
    "lib/chicago/flow/filter.rb",
    "lib/chicago/flow/mysql.rb",
    "lib/chicago/flow/mysql_file_serializer.rb",
    "lib/chicago/flow/mysql_file_sink.rb",
    "lib/chicago/flow/pipeline_endpoint.rb",
    "lib/chicago/flow/pipeline_stage.rb",
    "lib/chicago/flow/sink.rb",
    "lib/chicago/flow/transformation.rb",
    "lib/chicago/flow/transformation_chain.rb",
    "spec/array_sink_spec.rb",
    "spec/array_source_spec.rb",
    "spec/database.yml.dist",
    "spec/dataset_source_spec.rb",
    "spec/filter_spec.rb",
    "spec/mysql_file_serializer_spec.rb",
    "spec/mysql_file_sink_spec.rb",
    "spec/mysql_integration_spec.rb",
    "spec/pipeline_stage_spec.rb",
    "spec/spec_helper.rb",
    "spec/transformation_chain_spec.rb",
    "spec/transformation_spec.rb"
  ]
  s.homepage = "http://github.com/notonthehighstreet/chicago-flow"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Dataflow-style processing for hash-like rows"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
      s.add_runtime_dependency(%q<sequel_load_data_infile>, [">= 0.0.2"])
      s.add_runtime_dependency(%q<sequel_fast_columns>, [">= 0"])
      s.add_development_dependency(%q<mysql>, ["= 2.8.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2"])
      s.add_development_dependency(%q<bundler>, ["~> 1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<fastercsv>, [">= 0"])
      s.add_dependency(%q<sequel>, [">= 0"])
      s.add_dependency(%q<sequel_load_data_infile>, [">= 0.0.2"])
      s.add_dependency(%q<sequel_fast_columns>, [">= 0"])
      s.add_dependency(%q<mysql>, ["= 2.8.1"])
      s.add_dependency(%q<rspec>, ["~> 2"])
      s.add_dependency(%q<bundler>, ["~> 1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 0"])
    s.add_dependency(%q<sequel>, [">= 0"])
    s.add_dependency(%q<sequel_load_data_infile>, [">= 0.0.2"])
    s.add_dependency(%q<sequel_fast_columns>, [">= 0"])
    s.add_dependency(%q<mysql>, ["= 2.8.1"])
    s.add_dependency(%q<rspec>, ["~> 2"])
    s.add_dependency(%q<bundler>, ["~> 1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

